<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Ventasenc extends Model
{
    use HasFactory;
    protected $table = "lo_ventasenc";
    // protected $primaryKey = "idtipodocumento";
    public $incrementing = false;
    public $timestamps = false;
    protected $fillable=[
            "idempresa",
            "idtipodocumento",
            "serie",
            "numero",
            "idtipodocidentidad",
            "rucdni",
            "razon_social",
            "direccion",
            "ubigeo",
            "idtipotransaccion",
            "fecha_emision",
            "fecha_vencimiento",
            "idmoneda",
            "idformapago",
            "tipo_cambio",
            "porcentaje_igv",
            "descuento_global",
            "total_descuento",
            "total_anticipo",
            "total_gravado",
            "total_inafecto",
            "total_exonerado",
            "total_igv",
            "total_icbper",
            "total_gratuitas",
            "total_otros_cargos",
            "total",
            "idtipopercepcion",
            "percepcion_base",
            "total_percepcion",
            "total_incluido_percepcion",
            "afecto_detraccion",
            "observaciones",
            "idtipodocumentoref",
            "serie_ref",
            "numero_ref",
            "fecha_emision_ref",
            "idtiponotacredito",
            "idtiponotadebito",
            "enviado_sunat",
            "enviado_cliente",
            "cuo",
            "idcondicioncredito",
            "cuotas",
            "medio_de_pago",
            "orden_compra",
            "placa_vehiculo",
            "guia_remision",
            "detraccion_tipo",
            "detraccion_id",
            "detraccion_total",
            "detraccion_porcent",
            "afecto_retencion",
            "retencion_id",
            "retencion_total",
            "retencion_porcent",
            "ubigeo_origen",
            "direccion_origen",
            "ubigeo_destino",
            "direccion_destino",
            "detalle_viaje",
            "val_ref_serv_trans",
            "val_ref_carga_efec",
            "val_ref_carga_util",
            "total_isc",
            "idsucursal",
            "enviado",
            "error",
            "anulado",
            "fecha_creacion",
            "generado_automatico",
            "idorigen",
            "idvendedor",
            "efectivo",
            "optica",
            "optica_acuenta",
            "optica_importe_acta",
            "optica_cancelado",
            "optica_canjeado",
            "optica_documentoref",
            "por_consumo",
            "caja_IngEgr",
            "caja_fecha_pago",
            "caja_idtipodocumento",
            "caja_serie",
            "caja_numero",
            "caja_importe",
            "pasarela_idpago",
            "pasarela_fecha_pago",
            "pasarela_type",
            "pasarela_prorroga",
            "servicio_estado_pago",
            "cotizacion",
            "periodo",
            "idaniopro",
            "servicio_codeplex",
            "correlativo",
            "importado",
            "idturno",
            "cerrado_caja",
            "idusuario",
            "idcaja_apertura_cierre",
            "guia_emitida",
            "canje_doc_ref",
            "impreso"
    ];
}
